In [1]:
import numpy as np

In [14]:
L1 = [1,2,3]
L2 = [4,5,6]

L1 + L2

[1, 2, 3, 4, 5, 6]

In [13]:
L3 = []
for i in range(len(L1)):
    L3.append(L1[i]+L2[i])
L3

[5, 7, 9]

In [15]:
L1 = np.array([1,2,3])
L2 = np.array([4,5,6])

L1 + L2

array([5, 7, 9])

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.full(10,6)

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
A = np.random.randint(0,10,8)
A

array([7, 2, 9, 1, 6, 5, 6, 3])

In [25]:
A[0]

7

In [27]:
A[-1]

3

In [29]:
A[2:5]

array([9, 1, 6])

In [30]:
A[2:]

array([9, 1, 6, 5, 6, 3])

In [31]:
A[:2]

array([7, 2])

In [23]:
M = np.random.randint(-5,5,(5,5))
M

array([[ 3,  0, -3, -5, -2],
       [ 4,  3, -4, -3, -5],
       [-3, -5, -4,  0, -1],
       [ 3, -1,  0, -4,  4],
       [ 2, -4, -4, -2, -3]])

In [32]:
M[0,:]

array([ 3,  0, -3, -5, -2])

In [33]:
M[:,0]

array([ 3,  4, -3,  3,  2])

In [34]:
M[1,2]

-4

In [35]:
M[2:,2:4]

array([[-4,  0],
       [ 0, -4],
       [-4, -2]])

In [37]:
M + M

array([[  6,   0,  -6, -10,  -4],
       [  8,   6,  -8,  -6, -10],
       [ -6, -10,  -8,   0,  -2],
       [  6,  -2,   0,  -8,   8],
       [  4,  -8,  -8,  -4,  -6]])

In [38]:
M - M

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [40]:
M

array([[ 3,  0, -3, -5, -2],
       [ 4,  3, -4, -3, -5],
       [-3, -5, -4,  0, -1],
       [ 3, -1,  0, -4,  4],
       [ 2, -4, -4, -2, -3]])

In [39]:
M * M

array([[ 9,  0,  9, 25,  4],
       [16,  9, 16,  9, 25],
       [ 9, 25, 16,  0,  1],
       [ 9,  1,  0, 16, 16],
       [ 4, 16, 16,  4,  9]])

In [41]:
np.dot(M,M)

array([[ -1,  28,  11,   9, -17],
       [ 17,  52,  12,  -7, -16],
       [-19,   9,  49,  32,  38],
       [  1, -15, -21,  -4, -29],
       [-10,  22,  38,  16,  21]])

In [42]:
np.linalg.inv(M)

array([[-0.29652042,  0.12859304, -0.14447806,  0.15506808,  0.23827534],
       [-0.06656581,  0.19213313,  0.09001513,  0.05521936, -0.2322239 ],
       [ 0.37670197, -0.3827534 , -0.2934947 , -0.25567322,  0.14372163],
       [-0.49016641,  0.23298033,  0.02647504,  0.13388805,  0.10816944],
       [-0.28441755,  0.18456884,  0.15733737,  0.28139183, -0.12859304]])

In [43]:
np.linalg.det(M)

1321.9999999999995

In [44]:
np.sin(M)

array([[ 0.14112001,  0.        , -0.14112001,  0.95892427, -0.90929743],
       [-0.7568025 ,  0.14112001,  0.7568025 , -0.14112001,  0.95892427],
       [-0.14112001,  0.95892427,  0.7568025 ,  0.        , -0.84147098],
       [ 0.14112001, -0.84147098,  0.        ,  0.7568025 , -0.7568025 ],
       [ 0.90929743,  0.7568025 ,  0.7568025 , -0.90929743, -0.14112001]])

In [46]:
A

array([7, 2, 9, 1, 6, 5, 6, 3])

In [47]:
np.min(A)

1

In [48]:
np.max(A)

9

In [49]:
M

array([[ 3,  0, -3, -5, -2],
       [ 4,  3, -4, -3, -5],
       [-3, -5, -4,  0, -1],
       [ 3, -1,  0, -4,  4],
       [ 2, -4, -4, -2, -3]])

In [50]:
np.min(M)

-5

In [51]:
M

array([[ 3,  0, -3, -5, -2],
       [ 4,  3, -4, -3, -5],
       [-3, -5, -4,  0, -1],
       [ 3, -1,  0, -4,  4],
       [ 2, -4, -4, -2, -3]])

In [52]:
M.shape

(5, 5)

In [53]:
f,c = M.shape

In [54]:
O = np.zeros((f,c))
for i in range(f):
    for j in range(c):
        if(M[i,j]<0):
            O[i,j]=-1*M[i,j]
        else:
            O[i,j]=M[i,j]
            

In [55]:
O

array([[3., 0., 3., 5., 2.],
       [4., 3., 4., 3., 5.],
       [3., 5., 4., 0., 1.],
       [3., 1., 0., 4., 4.],
       [2., 4., 4., 2., 3.]])

In [59]:
M[M<0]=9

In [60]:
M

array([[3, 0, 9, 9, 9],
       [4, 3, 9, 9, 9],
       [9, 9, 9, 0, 9],
       [3, 9, 0, 9, 4],
       [2, 9, 9, 9, 9]])